### ISSUE TITLE
Failure to re-create persistent jobs on subsequent runs.

### ISSUE THREAD

**Issue by skolima** [dtinteractive/Topshelf.Integrations#18]
When job persistence is enabled (required e.g. in load-balanced setup), running any of the examples on the website will fail on the second run with:

```
2015-04-21 14:09:45,787 [1] INFO Quartz.Core.QuartzScheduler - JobFactory set to :
MyOwnJobFactory
Error: 0 : An exception occurred, Quartz.JobPersistenceException: Couldn't store job:
Unable to store Job: 'DEFAULT.MyOwnJobName', because one already exists with this identification.
---> Quartz.ObjectAlreadyExistsException:
Unable to store Job: 'DEFAULT.MyOwnJobName', because one already exists with this identification.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 907
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 920
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass16.<StoreJobsAndTriggers>b__15(ConnectionAndTransactionHolder conn) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 1130
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass73.<ExecuteInLock>b__72(ConnectionAndTransactionHolder conn) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3387
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3541
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3459
   at Quartz.Core.QuartzScheduler.ScheduleJobs(IDictionary`2 triggersAndJobs, Boolean replace) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\QuartzScheduler.cs:line 885
   at Topshelf.Quartz.ScheduleJobServiceConfiguratorExtensions.<>c__DisplayClassa`1.<ConfigureJob>b__3()
   at Topshelf.Runtime.EventCallbackList`1.Notify(T data)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run() [See nested exception: Quartz.ObjectAlreadyExistsException: Unable to store Job: 'DEFAULT.BusinessDevelopmentFeedProcessor', because one already exists with this identification.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 907]
```

Example Quartz config to get persistence enabled:

```xml
<quartz>
    <add key="quartz.scheduler.instanceName" value="MyInstanceName" />
    <add key="quartz.scheduler.instanceId" value="NON_CLUSTERED" />
    <add key="quartz.scheduler.interruptJobsOnShutdownWithWait" value="true" />
    <add key="quartz.threadPool.threadCount" value="5" />
    <add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" />
    <add key="quartz.jobStore.useProperties" value="true" />
    <add key="quartz.jobStore.dataSource" value="default" />
    <add key="quartz.jobStore.tablePrefix" value="QRTZ_" />
    <add key="quartz.jobStore.clustered" value="true" />
    <add key="quartz.jobStore.lockHandler.type" value="Quartz.Impl.AdoJobStore.SimpleSemaphore, Quartz" />
    <add key="quartz.dataSource.default.connectionStringName" value="ISASchema" />
    <add key="quartz.dataSource.default.provider" value="OracleODP-1123-40" />
    <add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.OracleDelegate, Quartz" />
  </quartz>
```

There's a pull request that fixes the issue: https://github.com/dtinteractive/Topshelf.Integrations/pull/9 , could it please get merged or reviewed? This pretty much prevents Topshelf.Quartz from being used with a persistent store.

**Comment by markhuber** [comment]
I'll try to get a look at it this week.

**Comment by markhuber** [comment]
Merged PR 9
